
all:
	g++ -DLINUX -std=c++11 codegen.cpp -o codegen.exe
	arm-linux-gnueabihf-g++ -DLINUX -I.. -L.. -L/root/raspi/vc/vc/lib -L/root/raspi/sdl2/SDL2-2.0.9/build/.libs -Wl,-rpath /root/raspi/vc/vc/lib -std=c++11 test.cpp -lGameApi -lpthread -lGLESv2 -lSDL2 -o test.exe

exe:
	(cd ..;cd editor; ../iot_main/test.exe)