#cp web_page_highmem.html /home/terop/html/meshpage.org/
cp web_page_highmem.worker.js /home/terop/html/meshpage.org/
#cp web_page_highmem.data /home/terop/html/meshpage.org/
cp web_page_highmem.js /home/terop/html/meshpage.org/
cp web_page_highmem.wasm /home/terop/html/meshpage.org/
cp web_page_highmem.wasm.br /home/terop/html/meshpage.org/
#cp web_page_highmem.wasm.map /home/terop/html/meshpage.org/
#cp web_page.html /home/terop/html/meshpage.org/
#cp web_page.data /home/terop/html/meshpage.org/
#cp web_page.js /home/terop/html/meshpage.org/
#cp web_page.wasm /home/terop/html/meshpage.org/
#cp web_page.wasm.br /home/terop/html/meshpage.org/
#cp web_page.wasm.map /home/terop/html/meshpage.org/
#cp pthread-main.js /home/terop/html/meshpage.org/
#cp web_page.worker.js /home/terop/html/meshpage.org/
#cp web_page_lowmem.html /home/terop/html/meshpage.org/
#cp web_page_lowmem.worker.js /home/terop/html/meshpage.org/
#cp web_page_lowmem.data /home/terop/html/meshpage.org/
#cp web_page_lowmem.js /home/terop/html/meshpage.org/
#cp web_page_lowmem.wasm /home/terop/html/meshpage.org/
#cp web_page_lowmem.wasm.br /home/terop/html/meshpage.org/
#cp web_page_lowmem.wasm.mem /home/terop/html/meshpage.org/
#cp web_page_nothreads_highmem.html /home/terop/html/meshpage.org/
#cp web_page_nothreads_highmem.data /home/terop/html/meshpage.org/
#cp web_page_nothreads_highmem.js /home/terop/html/meshpage.org/
#cp web_page_nothreads_highmem.wasm /home/terop/html/meshpage.org/
#cp web_page_nothreads_highmem.wasm.br /home/terop/html/meshpage.org/
#cp web_page_nothreads_highmem.wasm.map /home/terop/html/meshpage.org/
#cp web_page_nothreads.html /home/terop/html/meshpage.org/
#cp web_page_nothreads.data /home/terop/html/meshpage.org/
#cp web_page_nothreads.js /home/terop/html/meshpage.org/
#cp web_page_nothreads.wasm /home/terop/html/meshpage.org/
#cp web_page_nothreads.wasm.br /home/terop/html/meshpage.org/
#cp web_page_nothreads.wasm.map /home/terop/html/meshpage.org/
#cp web_page_lowmem_nothreads.data /home/terop/html/meshpage.org/
cp web_page_lowmem_nothreads.js /home/terop/html/meshpage.org/
cp web_page_lowmem_nothreads.wasm /home/terop/html/meshpage.org/
cp web_page_lowmem_nothreads.wasm.br /home/terop/html/meshpage.org/
echo COPIED SUCCESSFULLY


