
all:
	em++ -g --bind -std=c++11 -O2 test.cpp ..\libGameApi.bc -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_FREETYPE=1 -s DEMANGLE_SUPPORT=1 -L.. -L..\objs -I.. -o web_page_asmjs.html --preload-file logo.ppm --memory-init-file 0 -s DISABLE_EXCEPTION_CATCHING=1 --preload-file FreeSans.ttf -s ALLOW_MEMORY_GROWTH=1 -s "BINARYEN_TRAP_MODE='clamp'"