
all:
	em++ --bind -std=c++11 -O2 test.cpp ..\libGameApi.bc -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s DEMANGLE_SUPPORT=1 -s ALLOW_MEMORY_GROWTH=1 -L.. -L..\objs -I.. -o web_page.html --preload-file logo.ppm --memory-init-file 0 -s DISABLE_EXCEPTION_CATCHING=1 --closure 1 --llvm-lto 1 -s FORCE_FILESYSTEM=1 -s FULL_ES2=1