
CFiles=  GameApi_gltf.cc GameApi_diag.cc Pieces.cc Map.cc VectorTools.cc Effect.cc Buffer.cc \
	Intersect.cc Bitmap.cc Effect2.cc Shader.cc VolumeObjects.cc \
	Tree.cc Event.cc ObjectCreator.cc IntersectObject.cc Graph.cc \
	Widgets.cc Category.cc Plane.cc Coordinates.cc Triangle.cc Game.cc \
	Editor.cc Web.cc Functions.cc ShaderExpr.cc Font.cc FontEditor.cc \
	GameApiTest.cc Games.cc HierarchyObject.cc Physics.cc \
        GameApiTest2.cc State.cc Serialize.cc KeyFrameEditor.cc Parser.cc \
	VertexArray.cc StateChange.cc DistanceObject.cc GameRunner.cc \
	 GameApi_mx.cc GameApi_pc.cc \
	GameApi_phy.cc GameApi_pla.cc  GameApi_pt.cc \
	GameApi_an.cc  GameApi_co.cc GameApi_dr.cc GameApi_ev.cc \
	GameApi_ex.cc GameApi_fbo.cc GameApi_f.cc GameApi_fn.cc \
	GameApi_fnt.cc GameApi_gr.cc  GameApi_lay.cc \
	GameApi_pts.cc GameApi_sh.cc GameApi_shm.cc GameApi_sm.cc \
        GameApi_spa.cc GameApi_sp.cc GameApi_st.cc GameApi_su.cc \
        GameApi_tex.cc GameApi_tr.cc  GameApi_tx.cc \
        GameApi_vbo.cc GameApi_ve.cc GameApi_vo.cc GameApi_wmod.cc \
        GameApi_wv.cc GameApi_vx.cc GameApi_cut.cc GameApi_in.cc \
	GameApi_cmd_move.cc \
	GameApi_cmd_bbitmap.cc       GameApi_cmd_pdfield.cc \
	GameApi_cmd_bitmap.cc        GameApi_cmd_point.cc \
	GameApi_cmd_booleanops.cc    GameApi_cmd_points.cc \
	GameApi_cmd_cvolume.cc       GameApi_cmd_polygon2.cc \
	GameApi_cmd_fbitmap.cc       GameApi_cmd_polygon.cc \
	GameApi_cmd_font.cc          GameApi_cmd_framebuffer.cc \
	GameApi_cmd_texture.cc GameApi_cmd_fvolume.cc \
	GameApi_cmd_lines.cc         GameApi_cmd_vector.cc \
	GameApi_cmd_mainloop.cc      GameApi_cmd_volume.cc \
	GameApi_cmd_material.cc      GameApi_cmd_waveform.cc GameApi_cmd_shader.cc \
	GameApi_cmd.cc cpushader.cc \
draco/attributes/attribute_octahedron_transform.cc    draco/attributes/geometry_attribute.cc \
draco/attributes/attribute_quantization_transform.cc  draco/attributes/point_attribute.cc \
draco/attributes/attribute_transform.cc \
draco/compression/decode.cc                          draco/compression/encode.cc         \
draco/compression/draco_compression_options.cc       draco/compression/expert_encode.cc \
draco/compression/attributes/attributes_encoder.cc \
draco/compression/attributes/sequential_attribute_decoder.cc \
draco/compression/attributes/sequential_attribute_decoders_controller.cc \
draco/compression/attributes/sequential_attribute_encoder.cc \
draco/compression/attributes/sequential_attribute_encoders_controller.cc \
draco/compression/attributes/sequential_integer_attribute_decoder.cc \
draco/compression/attributes/sequential_integer_attribute_encoder.cc \
draco/compression/attributes/sequential_normal_attribute_decoder.cc \
draco/compression/attributes/sequential_normal_attribute_encoder.cc \
draco/compression/attributes/sequential_quantization_attribute_decoder.cc \
draco/compression/attributes/sequential_quantization_attribute_encoder.cc \
draco/compression/attributes/prediction_schemes/prediction_scheme_encoder_factory.cc \
draco/compression/bit_coders/adaptive_rans_bit_decoder.cc  draco/compression/bit_coders/direct_bit_encoder.cc   \
draco/compression/bit_coders/adaptive_rans_bit_encoder.cc  draco/compression/bit_coders/rans_bit_decoder.cc    draco/compression/bit_coders/symbol_bit_decoder.cc \
draco/compression/bit_coders/direct_bit_decoder.cc         draco/compression/bit_coders/rans_bit_encoder.cc    draco/compression/bit_coders/symbol_bit_encoder.cc \
draco/compression/entropy/shannon_entropy.cc       draco/compression/entropy/symbol_encoding.cc \
draco/compression/entropy/symbol_decoding.cc \
draco/compression/mesh/mesh_decoder.cc                \
draco/compression/mesh/mesh_edgebreaker_decoder.cc       draco/compression/mesh/mesh_encoder.cc \
draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc  \
draco/compression/mesh/mesh_edgebreaker_encoder.cc       draco/compression/mesh/mesh_sequential_decoder.cc \
draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc  draco/compression/mesh/mesh_sequential_encoder.cc \
draco/compression/point_cloud/point_cloud_decoder.cc        \
draco/compression/point_cloud/point_cloud_encoder.cc \
draco/compression/point_cloud/point_cloud_sequential_decoder.cc \
draco/compression/point_cloud/point_cloud_kd_tree_decoder.cc \
draco/compression/point_cloud/point_cloud_sequential_encoder.cc \
draco/compression/point_cloud/point_cloud_kd_tree_encoder.cc \
draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.cc  draco/compression/point_cloud/algorithms/float_points_tree_encoder.cc \
draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_encoder.cc  draco/compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc \
draco/compression/point_cloud/algorithms/float_points_tree_decoder.cc               draco/compression/point_cloud/algorithms/integer_points_kd_tree_encoder.cc \
draco/core/bit_utils.cc               draco/core/divide.cc            draco/core/options.cc \
draco/core/bounding_box.cc            draco/core/quantization_utils.cc \
draco/core/draco_types.cc      \
draco/core/cycle_timer.cc             draco/core/encoder_buffer.cc    draco/core/status.cc \
draco/core/data_buffer.cc             draco/core/hash_utils.cc     \
draco/core/decoder_buffer.cc       \
draco/mesh/corner_table.cc                 draco/mesh/mesh_misc_functions.cc    draco/mesh/mesh_splitter.cc \
draco/mesh/mesh_are_equivalent.cc          draco/mesh/mesh_stripifier.cc \
draco/mesh/mesh_attribute_corner_table.cc  \
draco/mesh/mesh.cc                         draco/mesh/mesh_utils.cc \
draco/mesh/mesh_cleanup.cc                \
draco/mesh/triangle_soup_mesh_builder.cc \
draco/mesh/mesh_features.cc  \
draco/point_cloud/point_cloud_builder.cc       draco/point_cloud/point_cloud.cc \
draco/compression/attributes/kd_tree_attributes_decoder.cc \
draco/compression/attributes/kd_tree_attributes_encoder.cc \
draco/metadata/geometry_metadata.cc  draco/metadata/metadata_encoder.cc       draco/metadata/property_table.cc     \
draco/metadata/metadata.cc     \
draco/metadata/metadata_decoder.cc          draco/metadata/structural_metadata.cc \
draco/compression/attributes/attributes_decoder.cc
#lib/lib_webgpu.cc \
#lib/lib_webgpu_cpp20.cc \
#webgpu.cc


DEBUGFILES = FreeType.cc FreeType2.cc GameApi_gui.cc GameApi.cc GameApi_bm.cc \
	GameApi_pl.cc GameApi_trk.cc  GameApi_li.cc GameApi_main.cc \
	GameApi_imp.cc GameApi_plane.cc GameApi_integrator.cc Main.cc GameApi_vr.cc GameApi_low.cc GameApi_dep_add_find.cc GameApi_dep_env.cc GameApi_dep_arr_render.cc GameApi_webcam.cc Math2.cc GameApi_dep_store.cc 

OLDCFiles=music.c music_html5.c prerequisites.c

OFiles = $(patsubst %.cc,objs/%.bc,$(CFiles))
DOFiles = $(patsubst %.cc,objs/%.bc,$(DEBUGFILES))
OOFiles = $(patsubst %.c,objs/%.bc,$(OLDCFiles))
O2Files = $(patsubst %.cc,objs/%.bc,$(CFiles2))
DWOFiles = $(patsubst %.cc,objs/%.dwo,$(CFiles))
DWDOFiles = $(patsubst %.cc,objs/%.dwo,$(DEBUGFILES))
DWOOFiles = $(patsubst %.c,objs/%.dwo,$(OLDCFiles))
DWO2Files = $(patsubst %.cc,objs/%.dwo,$(CFiles2))
OFiles_nothreads = $(patsubst %.cc,objs/nothreads/%.bc,$(CFiles))
DOFiles_nothreads = $(patsubst %.cc,objs/nothreads/%.bc,$(DEBUGFILES))
OOFiles_nothreads = $(patsubst %.c,objs/nothreads/%.bc,$(OLDCFiles))
O2Files_nothreads = $(patsubst %.cc,objs/nothreads/%.bc,$(CFiles2))

DWOFiles_nothreads = $(patsubst %.cc,objs/nothreads/%.dwo,$(CFiles))
DWDOFiles_nothreads = $(patsubst %.cc,objs/nothreads/%.dwo,$(DEBUGFILES))
DWOOFiles_nothreads = $(patsubst %.c,objs/nothreads/%.dwo,$(OLDCFiles))
DWO2Files_nothreads = $(patsubst %.cc,objs/nothreads/%.dwo,$(CFiles2))

DFiles = $(patsubst %.cc,objs/%.d,$(CFiles)) 
D2Files = $(patsubst %.cc,objs/%.d2,$(CFiles2)) 
HFiles = $(patsubst %.cc,%.hh,$(CFiles))
Subdirsx = $(patsubst %,%build,$(Subdirs))

OFiles_examples = $(patsubst %.cc,objs/%.bc,$(CFiles_examples))
O2Files_examples = $(patsubst %.cc,objs/%.bc,$(CFiles2_examples))
DFiles_examples = $(patsubst %.cc,objs/%.d,$(CFiles_examples)) 
D2Files_examples = $(patsubst %.cc,objs/%.d2,$(CFiles2_examples)) 
HFiles_examples = $(patsubst %.cc,%.hh,$(CFiles_examples))


all:
	@echo "choose either grow, lowmem, both or pthreads_grow"

#-s MAXIMUM_MEMORY=4GB -s ALLOW_MEMORY_GROWTH=1  // doesnt work in firefox.
#-fsanitize=address (causes slowness/fps broken)

PTHREADOPT = -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=8


# -Oz
SIZEOPT=-gpubnames --profiling-funcs -O3   -s TOTAL_STACK=38800kb -s DISABLE_EXCEPTION_CATCHING=0  -sREVERSE_DEPS=all

# -fno-rtti -fno-exceptions -gpubnames -s FILESYSTEM=0

NOSIZEOPT = -s TOTAL_STACK=38800kb

#
#--closure 1
#--memoryprofiler
# -gpubnames
# -fno-rtti
# 'ALLOC_DYNAMIC', 'ALLOC_NONE', '_activate_trigger', 'set_toggle_button', 'FT_GET_Char_Index', 'FT_Load_Glyph', 'FT_New_Memory_Faces', 'FT_Render_Glyph', 'FT_Set_Char_Size', 'emscripten_fetch', 'emscripten_fetch_attr_init', 'emscripten_fetch_close', '_set_float',  '_get_integer', '_set_integer', '_set_float', '_set_string', '_set_resize_event', '_stop_music_playing', '_set_background_mode', '_set_new_script'
REQUIREDOPT = -fno-rtti -DEMSCRIPTEN -s SHARED_MEMORY=1 -s MAXIMUM_MEMORY=4gb -s ALLOW_MEMORY_GROWTH=1 -s TOTAL_MEMORY=50Mb -Wno-unused-command-line-argument -emit-llvm   -s WASM=1 -s "EXPORTED_RUNTIME_METHODS=['miniTempWebGLIntBuffers', 'removeRunDependency','UTF8ToString','allocate', 'ALLOC_NORMAL', 'ALLOC_STACK', 'cwrap', 'ccall']" -s "EXPORTED_FUNCTIONS=['_malloc', '_free', '_main', '_set_float', '_get_integer', '_set_integer', '_set_float', '_set_string', '_set_resize_event', '_stop_music_playing', '_set_background_mode', '_set_new_script']" -s ALLOW_BLOCKING_ON_MAIN_THREAD=1 -s USE_SDL_MIXER=2 -s DEFAULT_LIBRARY_FUNCS_TO_INCLUDE='stackTrace'  -s WASM=1 -s STACK_OVERFLOW_CHECK=0 -s ASSERTIONS=1 -s WASM_OBJECT_FILES=1 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s ELIMINATE_DUPLICATE_FUNCTIONS=1

OPENCVOPT = -L./emscriptendeps/build_wasm3/lib \
	  ./emscriptendeps/build_wasm3/lib/libopencv_core.a \
	  ./emscriptendeps/build_wasm3/lib/libopencv_video.a \
	  ./emscriptendeps/build_wasm3/lib/libopencv_videoio.a \
	  ./emscriptendeps/build_wasm3/lib/libopencv_imgproc.a \
	  ./emscriptendeps/build_wasm3/lib/libopencv_imgcodecs.a \
	  -s SHARED_MEMORY=1 -s FETCH_SUPPORT_INDEXEDDB=0 -s NO_DISABLE_EXCEPTION_CATCHING -sASSERTIONS=0 -sSAFE_HEAP=0

	  #./emscriptendeps/build_wasm3/lib/libopencv_calib3d.a 
	  #./emscriptendeps/build_wasm3/lib/libopencv_dnn.a
	  #./emscriptendeps/build_wasm3/lib/libopencv_features2d.a
	  #./emscriptendeps/build_wasm3/lib/libopencv_flann.a
	  #./emscriptendeps/build_wasm3/lib/libopencv_objdetect.a
	  #./emscriptendeps/build_wasm3/lib/libopencv_photo.a


STRIP = echo emstrip --no-strip-all --remove-section=name

#
#-g   (doesnt work with closure compiler)

ALLFLAGS = $(SIZEOPT) $(REQUIREDOPT) $(OPENCVOPT)
PTHREADOPT2 = $(PTHREADOPT)


# --use-preload-cache
# --preload-file web_page/logo-connecting.raw --preload-file web_page/logo-downloading.raw --preload-file web_page/logo-preparing.raw
# -s USE_SDL_MIXER=2 -s USE_OGG=1 -s USE_MP3=1
# -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=30
# -fno-exceptions
# -g -gsource-map --source-map-base https://meshpage.org/gameapisource/
# -s DEMANGLE_SUPPORT=1
# -fno-rtti -fno-exceptions
# -s DISABLE_EXCEPTION_CATCHING=0
# '__cxa_is_pointer_type', '__cxa_can_catch',
# -fno-exceptions -s DISABLE_RTTI=1
# -fimplicit-modules -fimplicit-module-maps
# -s TOTAL_STACK=20Mb
# --closure 1
# -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib

both:  both_lowmem both_highmem

# -s FILESYSTEM=0
# -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib  -s TOTAL_MEMORY=1920bM
both_highmem: test.cpp ../libGameApi_nothreads.bc
	@echo "  LINK   web_page/engine_nothreads_highmem.js"
	@(cd ..;em++ $(ALLFLAGS)   --use-preload-cache --bind -std=c++11 web_page/test.cpp $(OFiles_nothreads) $(DOFiles_nothreads) $(OOFiles_nothreads) $(O2Files_nothreads) -s USE_SDL=2  -s USE_FREETYPE=1   -L. -Lobs -I. -o web_page/engine_nothreads_highmem.js -s ERROR_ON_UNDEFINED_SYMBOLS=0  -s ENVIRONMENT=web,worker -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s FETCH=1  -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0 )
	@echo "  BROTLI engine_nothreads_highmem.wasm.br"
	@brotli --quality=5 --force engine_nothreads_highmem.wasm -o engine_nothreads_highmem.wasm.br

#   -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=920Mb
#  -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=220Mb -s FILESYSTEM=0
both_lowmem: test.cpp ../libGameApi_nothreads.bc
	@echo "  LINK   web_page/engine_lowmem_nothreads.js"
	@(cd ..;em++ $(ALLFLAGS)     --use-preload-cache --bind -std=c++11 web_page/test.cpp $(OFiles_nothreads) $(DOFiles_nothreads) $(OOFiles_nothreads) $(O2Files_nothreads) -s USE_SDL=2  -s USE_FREETYPE=1  -L. -Lobs -I. -o web_page/engine_lowmem_nothreads.js -s ERROR_ON_UNDEFINED_SYMBOLS=0   -s ENVIRONMENT=web,worker -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s FETCH=1  -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0 )
	@echo "  BROTLI engine_lowmem_nothreads.wasm.br"
	@brotli --quality=5 --force engine_lowmem_nothreads.wasm -o engine_lowmem_nothreads.wasm.br


pthreads_both: pthreads_both_highmem
#pthreads_both_middlemem pthreads_both_lowmem

# -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=1750Mb -s FILESYSTEM=0
pthreads_both_highmem: test.cpp ../libGameApi.bc
	@echo "  LINK   web_page/engine_highmem.js"
	@(cd ..;em++ $(PTHREADOPT2) $(ALLFLAGS)     --use-preload-cache  -s NO_EXIT_RUNTIME=1   --bind -std=c++11 web_page/test.cpp $(OFiles) $(DOFiles) $(OOFiles) $(O2Files) -s USE_SDL=2  -s USE_FREETYPE=1 -L. -Lobs -I. -o web_page/engine_highmem.js -s ERROR_ON_UNDEFINED_SYMBOLS=0   -s ENVIRONMENT=web,worker -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s FETCH=1  -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0  )
	@echo "  BROTLI engine_highmem.wasm.br"
	@brotli --quality=5 --force engine_highmem.wasm -o engine_highmem.wasm.br

#  -Lhssynth2/synthlib/emscripten -lsynthlib -L hssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=950Mb


# -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=220Mb

#-Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=1920Mb -s FILESYSTEM=0
# -fno-exceptions
both_nodebug_highmem: test.cpp ../libGameApi_nothreads.bc 
	@echo "  LINK   web_page/engine_nothreads_highmem.js"
	@(cd ..;em++ $(ALLFLAGS)  -fimplicit-modules -fimplicit-module-maps    --use-preload-cache --bind -std=c++11 web_page/test.cpp $(OFiles_nothreads) $(DOFiles_nothreads) $(OOFiles_nothreads) $(O2Files_nothreads) -s USE_SDL=2 -s USE_FREETYPE=1   -L. -Lobs -I. -o web_page/engine_nothreads_highmem.js -s ERROR_ON_UNDEFINED_SYMBOLS=0   -s ENVIRONMENT=web,worker -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s FETCH=1  -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0  )
	@echo "  BROTLI engine_nothreads_highmem.wasm.br"
	@brotli --quality=5 --force engine_nothreads_highmem.wasm -o engine_nothreads_highmem.wasm.br


#-Lhssynth2/synthlib/emscripten -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib


# -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=920Mb -s TOTAL_MEMORY=220Mb -s FILESYSTEM=0
# -fno-exceptions
both_nodebug_lowmem: test.cpp ../libGameApi_nothreads.bc 
	@echo "  LINK   web_page/engine_lowmem_nothreads.js"
	@(cd ..;em++ $(ALLFLAGS)  -fimplicit-modules -fimplicit-module-maps    --use-preload-cache --bind -std=c++11 web_page/test.cpp $(OFiles_nothreads) $(DOFiles_nothreads) $(OOFiles_nothreads) $(O2Files_nothreads) -s USE_SDL=2  -s USE_FREETYPE=1   -L. -Lobs -I. -o web_page/engine_lowmem_nothreads.js -s ERROR_ON_UNDEFINED_SYMBOLS=0   -s ENVIRONMENT=web,worker -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s FETCH=1  -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0  )   
	@echo "  BROTLI engine_lowmem_nothreads.wasm.br"
	@brotli --quality=5 --force engine_lowmem_nothreads.wasm -o engine_lowmem_nothreads.wasm.br


pthreads_both_nodebug: pthreads_both_nodebug_highmem pthreads_both_nodebug_middlemem pthreads_both_nodebug_lowmem

# -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib -s TOTAL_MEMORY=1950Mb -s FILESYSTEM=0 
# -fno-exceptions
pthreads_both_nodebug_highmem: test.cpp ../libGameApi.bc
	@echo "  LINK   web_page/engine_highmem.js"
	@(cd ..;em++ $(ALLFLAGS)  -fimplicit-modules -fimplicit-module-maps   --use-preload-cache -s NO_EXIT_RUNTIME=1  --bind -std=c++11 web_page/test.cpp $(OFiles) $(DOFiles) $(OOFiles) $(O2Files) -s USE_SDL=2  -s USE_FREETYPE=1  -L. -Lobs -I. -o web_page/engine_highmem.js -s ERROR_ON_UNDEFINED_SYMBOLS=0  -s ENVIRONMENT=web,worker -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1 -s FETCH=1  -s MIN_WEBGL_VERSION=2 -s MAX_WEBGL_VERSION=2 -s GL_SUPPORT_AUTOMATIC_ENABLE_EXTENSIONS=0 )
	@echo "  BROTLI engine_highmem.wasm.br"
	@brotli --quality=5 --force engine_highmem.wasm -o engine_highmem.wasm.br

# -Lhssynth2/synthlib/emscripten -lsynthlib -Lhssynth2/midiplay/midifile/emscripten -lmidifilelib  -s TOTAL_MEMORY=950Mb


#-s NO_DISABLE_EXCEPTION_CATCHING
#TOTAL MEMORY in different browsers:
#firefox 1920Mb OK
#firefox-esr78.0: 920Mb OK (testaa ~/cvs/firefox-esr/firefox hakemiston browserilla)
#chrome 1920Mb OK
