cp mesh_test.php /home/terop/html/meshpage.org/
cp mesh_display.php /home/terop/html/meshpage.org/
cp cookies.php /home/terop/html/meshpage.org/
cp mesh_background.php /home/terop/html/meshpage.org/
cp mesh_addtext.php /home/terop/html/meshpage.org/
cp builder_display.php /home/terop/html/meshpage.org/
cp mesh_stats.php /home/terop/html/meshpage.org/
cp mesh_pre.php /home/terop/html/meshpage.org/
cp mesh_api.php /home/terop/html/meshpage.org/
cp mesh_embed.php /home/terop/html/meshpage.org/
cp mesh_clickable.php /home/terop/html/meshpage.org/
cp mesh_server.php /home/terop/html/meshpage.org/
cp mesh_css.css /home/terop/html/meshpage.org/
cp mesh_css_mobile.css /home/terop/html/meshpage.org/
cp mesh_hide.php /home/terop/html/meshpage.org/
cp mesh_hide_action.php /home/terop/html/meshpage.org/
cp mesh_block.php /home/terop/html/meshpage.org/
cp mesh_block_action.php /home/terop/html/meshpage.org/
cp mesh_code.php /home/terop/html/meshpage.org/
cp mesh_faq.php /home/terop/html/meshpage.org/
cp user.php /home/terop/html/meshpage.org/
cp user_page.php /home/terop/html/meshpage.org/
cp create_mesh.php /home/terop/html/meshpage.org/
cp emscripten_frame.php /home/terop/html/meshpage.org/
#cp mesh.php /home/terop/html/meshpage.org/
cp mesh_preview.php /home/terop/html/meshpage.org/
cp action_new_mesh.php /home/terop/html/meshpage.org/
cp action_progress_mesh.php /home/terop/html/meshpage.org/
cp builder.php /home/terop/html/meshpage.org/
cp source_table.php /home/terop/html/meshpage.org/
cp save_screenshot.php /home/terop/html/meshpage.org/
cp load_url.php /home/terop/html/meshpage.org/
cp load_date.php /home/terop/html/meshpage.org/
cp mesh_save.php /home/terop/html/meshpage.org/
cp mesh_all.php /home/terop/html/meshpage.org/
cp mesh_tool.php /home/terop/html/meshpage.org/
cp index.html /home/terop/html/meshpage.org/ 
cp mesh_about.php /home/terop/html/meshpage.org/
cp mesh_login.php /home/terop/html/meshpage.org/
cp mesh_logout.php /home/terop/html/meshpage.org/
cp mesh_login_result.php /home/terop/html/meshpage.org/
cp mapping.txt /home/terop/html/meshpage.org/
cp mesh_tutorial.php /home/terop/html/meshpage.org/
cp mesh_detect.php /home/terop/html/meshpage.org/
cp mesh_html.php /home/terop/html/meshpage.org/
