<?php

header("Cross-Origin-Opener-Policy: same-origin");

$labels = array("3D MODEL VIEWER", "GLTF to HTML5 ZIP", "FULL CUSTOMISATION", "EXAMPLES");
$imgs = array("img_1.webp", "img_2.webp", "img_3.webp", "img_4.webp");
$alts = array("3d model viewer", "gltf to html5 zip converter", "builder tool download", "3d design examples");
$links = array("view.php", "gltf_to_zip.php", "meshpage_4", "meshpage.php");
$descs = array("quickly test that your <br>gltf files are<br>compatible<br> with the engine",
       	       "convert your<br>gltf files to html5<br>for hosting space<br>deployment",
	       "if end result needed<br>tweaking, use full<br> customisation",
	       "and there's plenty<br> of examples to learn<br> the scripting language");


  $logstr = $_SERVER["HTTP_REFERER"];
if ($logstr != "https://meshpage.org/assets/homepage/homepage.php" && $logstr != "")
{
$fp = fopen("./pp2/referer.log","a+");
fwrite($fp, "MAINPAGE " . $logstr);
fclose($fp);
}

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<title>A way to display your 3d models on the web -- jpg of 3d</title>\n";
echo "<head>\n";
echo "<meta name=\"description\" content=\"Getting the best rendering result from gltf files is not easy task, but we're now getting the best result available on the market.\">\n";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=0.7\">\n";
echo "</head>\n";
echo "<body>\n";

//echo "SEO_KEYWORDS: meshpage.org offers unique way to do physically based rendering via runtime processing of 3d assets from normal gltf 2.0 files. The 3d models are created in blender and its gltf exporter and passed to our asset delivery system. This uses khronos group gltf 2.0 standard and can render 3d models from multiple sources, including blender and sketchfab.";

//echo "<img src=\"gnome.webp\" width=\"300px\" height=\"150px\" style=\"position:absolute; top:1px; right:0px;\"/>";
echo "<div class=\"image-wrapper\">\n";
echo "<img style=\"border-radius: 30px; border-width: 2px; border-style: solid; width:100%; height: auto; top: 0px; left: 0px; z-order: -1;\" src=\"https://meshpage.org/sheepgame1.webp\" width=\"100%\"/>\n";
echo "</div>\n";

echo "<div style=\"left: 80px;\" class=\"media\">\n";
echo "<div>\n";
echo "<h1 class=\"customfont hardshadow fontsize orange\" align=\"left\" style=\"position: static; left: -120px;\">MESHPAGE.ORG&reg;</h1>\n";
echo "<h2 class=\"customfont hardshadow label_a white\" align=\"left\" style=\"position: relative; top: -50px; left: 50px; font-size: 14px;\">(A way to display your 3d models on the web -- jpg of 3d)</h2>\n";

echo "</div>\n";
echo "</div>\n";
echo "<div class=\"bl_container\">\n";
echo "<div class=\"bl_row\">\n";
echo "<div class=\"bl_column\">\n";
echo "<div class=\"bl_item customfont content\">\n";
echo "<h2>SUITABLE EXTERNAL TOOLS:</h2> <a href=\"https://www.blender.org/download/\">blender</a>, <a href=\"https://sketchfab.com/feed\">sketchfab</a>, <a href=\"https://meshy.ai\">meshy</a>.\n";
echo "</div>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div class=\"bl_row\">\n";
echo "<div class=\"bl_column\">\n";
echo "<div class=\"bl_item customfont content\">\n";
echo "<h2>USE CASES SUPPORTED:</h2>\n";
echo "<ul>\n";
echo "<li>Display 3d models in linux,win32,web,android\n";
echo "<li>GLTF imports from blender,sketchfab,meshy\n";
echo "<li>Exports to script.txt,html5 zip files,android apk files\n";
echo "<li>Running the script.txt via builder, web deploy, cmdline tool in ubuntu/win32, or in wine\n";
echo "<li>Html5 export has video canvas or embedding, full screen mode\n";
echo "<li>File format support like .obj,.stl,.glb,.gltf\n";
echo "<li>GLTF Materials, skeletons/rigging, animations\n";
echo "<li>OpenGL instancing, static instancing\n";
echo "<li>Load time and frame rate performance optimizations\n";
echo "<li>Concurrent network stack,zip decode,image decode,vertex arrays,textures using 8 cpus after web deploy\n";
echo "<li>Large 3d model support with sanmiguel and sponza working\n";
echo "<li>Light and shadow support with phong lighting model\n";
echo "<li>Creating larger worlds from smaller pieces in precalc time\n";
echo "<li>Combining multiple 3d models to the same scene\n";
echo "<li>Moving and animating 3d models\n";
echo "<li>Changing colours and materials of the 3d models\n";
echo "<li>Node graph based builder tool for editing codegen scripts\n";
echo "<li>Zoom/Rotate controls, quake movements, wasd movement etc...\n";
echo "</ul>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div class=\"bl_column\">\n";
echo "<div class=\"bl_item content\">\n";
echo "<img class=\"bl_img\" src=\"https://meshpage.org/row1.webp\"/>\n";
echo "</div>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div class=\"bl_row\">\n";
echo "<div class=\"bl_column\">\n";
echo "<div class=\"bl_item content\">\n";
echo "<img clasS=\"bl_img\" src=\"https://meshpage.org/row2.webp\"/>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div class=\"bl_column\">\n";
echo "<div class=\"bl_item customfont content\">\n";
echo "<br><h2>PROBLEM AREAS:</h2>\n";
echo "<ul>\n";
echo "<li>Meshy rigging doesnt work in meshpage\n";
echo "<li>GLTF animations have problems in some models\n";
echo "<li>GLTF cameras not implemented\n";
echo "<li>GLTF material light direction not implemented\n";
echo "<li>Water shader is based on hacks instead of navier-stokes\n";
echo "<li>Blender import is known to contain areas that cannot be rendered\n";
echo "<li>Phong shading is already outdated\n";
echo "<li>File size limits at 250Mb sketchfab zip file size\n";
echo "<li>Builder is unusable for newbies\n";
echo "<li>Android deliverables require installation of ndk and a working build\n";
echo "</ul>\n";
echo "</div>\n";
echo "</div>\n";

echo "</div>\n";
echo "<div class=\"bl_row\">\n";
echo "<div class=\"bl_column\">\n";
echo "<div class=\"bl_item customfont content\">\n";
echo "<br><h2>FEATURES STILL IN THE FUTURE:</h2>\n";
echo "<ul>\n";
echo "<li>raspi support(memory problems)\n";
echo "<li>vulkan or webgpu support(not implemented)\n";
echo "<li>virtual reality and augmented reality(was implemented, doesnt work)\n";
echo "<li>ray tracing support(opengl drivers doesnt exist)\n";
echo "<li>path tracing support(implementation not started)\n";
echo "<li>cloud rendering support(implementation not started)\n";
echo "<li>nanite(implementation not started)\n";
echo "<li>robot spare parts display(waiting for hw availability)\n";
echo "<li>nft and e-commerce support(implementation not started)\n";
echo "<li>popularity(access to popular sales platforms missing(I'm not going to spam people with useless emails))\n";
echo "<li>video support(rejected for copyright reasons)\n";
echo "<li>artificial intelligence(not enough information how to implement/database copyright problems)\n";
echo "</ul>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div class=\"bl_column\">\n";
echo "<div class=\"bl_item content\">\n";
echo "<img class=\"bl_img\" src=\"https://meshpage.org/row3.webp\"/>\n";
echo "</div>\n";
echo "</div>\n";

echo "</div>\n";


echo "<div class=\"bl_row\">\n";
echo "<div class=\"bl_column\">\n";

echo "<div class=\"bl_item img\">\n";
echo "<iframe class=\"bl_iframe\" scrolling=\"no\" seamless=\"seamless\" allow=\"cross-origin-isolated\" src=\"https://meshpage.org/punk/index.html\" width=\"800\" height=\"440\" style=\"overflow: visible; border: none;\"></iframe>\n";
echo "</div></div>\n";
echo "<div class=\"bl_column\"><div class=\"bl_item customfont content\">\n";
echo "<a href=\"https://meshpage.org/punk/gnome.zip\">gnome.zip</a>(<a href=\"#gnomeauthor\">*</a>) (We wanted this: <a href=\"https://meshpage.org/assets/gnome2.webp\">gnome2</a>)\n";
echo "<pre class=\"customfont\" style=\"font-size: 14px;\">\n";
echo "TF I1=ev.mainloop_api.gltf_loadKK2(https://meshpage.org/punk/mesh_garden_gnome.glb);\n";
echo "P I2=ev.mainloop_api.gltf_mesh_all_p(ev,I1);\n";
echo "P I3=ev.polygon_api.color_alpha(I2,ff);\n";
echo "MT I4=ev.materials_api.colour_material(ev,0);\n";
echo "MT I5=ev.materials_api.toon_border(ev,I4,2,ff000000,true);\n";
echo "MT I6=ev.materials_api.gltf_material(ev,I1,0,1.5,400,-400,300);\n";
echo "MT I7=ev.materials_api.combine_materials(ev,I4,I6);\n";
echo "MT I8=ev.materials_api.combine_materials(ev,I5,I7);\n";
echo "MT I9=ev.materials_api.colour_material(ev,0.1);\n";
echo "MT I100=ev.materials_api.phong(ev,I9,30,-30,300,ff000000,ffffffff,120);\n";
echo "MT I110=ev.materials_api.combine_materials(ev,I8,I100);\n";
echo "ML I120=ev.materials_api.bind(I3,I110);\n";
echo "MN I10=ev.move_api.mn_empty();\n";
echo "MN I11=ev.move_api.scale2(I10,2,2,2);\n";
echo "MN I12=ev.move_api.rotate(I11,0,30,0,0,0,0,1,0,1.57);\n";
echo "MN I13=ev.move_api.rotate(I12,30,100,0,0,0,0,1,0,-3.141);\n";
echo "MN I14=ev.move_api.rotate(I13,100,130,0,0,0,0,1,0,1.57);\n";
echo "MN I15=ev.move_api.time_repeat(I14,0,130);\n";
echo "ML I16=ev.move_api.move_ml(ev,I120,I15,1,10.0);\n";
echo "ML I17=ev.mainloop_api.scene_transparency(I16);\n";
echo "ML I18=ev.mainloop_api.async_gltf(I17,I1);\n";
echo "RUN I19=ev.blocker_api.game_window2(ev,I18,false,false,0.0,100000.0);\n";
echo "</pre>\n";
echo "</div>\n";
echo "</div>\n";
echo "</div>\n";
echo "</div>\n";
echo "</div>\n";
echo "<div style=\"height:50px;\"></div>";
echo "<div class=\"customfont\" style=\"position: relative; left:30px;\">\n";
echo "<h1>AVAILABLE TOOLS:</h1>\n";
echo "</div>\n";
echo "<div class=\"grid_container\">\n";
for($i=0;$i<4;$i++)
{
   echo "<div class=\"grid_item\">\n";
   echo "<a class=\"link\" href=\"$links[$i]\">\n";
   echo "<div class=\"grid_elem\">\n";
   echo "<div class=\"grid_item1 width320 customfont\" style=\"font-size: 40px;\">\n";
   echo "<strong>$labels[$i]</strong>\n";
   echo "</div>\n";
   echo "<div class=\"grid_item2 center width150\">\n";
   echo "<img class=\"imgs2\" src=\"$imgs[$i]\" width=\"150\" height=\"110\" alt=\"$alts[$i]\"\/>\n";
   echo "</div>\n";

if (substr_count($descs[$i],"<br>")>=3) {
   echo "<div class=\"grid_item3 width200 customfont\" style=\"font-size: 20px; margin: 15px 5px 5px 0px\">\n";
   } else {
   echo "<div class=\"grid_item3 width200 customfont\" style=\"font-size: 20px; margin: 25px 5px 5px 0px\">\n";
   }
   echo "$descs[$i]\n";
   echo "</div>\n"; // grid item3
   echo "</div>\n"; // grid_elem
   echo "</a>\n";
   echo "</div>\n"; // grid_item

}
echo "</div>\n";



echo "<style>\n";
echo "html, body {\n";
echo "    max-width: 100%;\n";
echo "    overflow-x: hidden;\n";
echo "}\n";
echo "::-webkit-scrollbar {\n";
echo "    width: 0px;\n";
echo "    height: 0px;\n";
echo "}\n";
echo ".media {\n";
echo "position:absolute;\n";
echo "  top: 20%;\n";
echo "}\n";
echo "@media only screen and (min-width: 800px) {\n";
echo ".media {\n";
echo "position:absolute;\n";
echo "  top: 40%;\n";
echo "}\n";
echo "}\n";
echo "@media only screen and (min-width: 1000px) {\n";
echo ".media {\n";
echo "position:absolute;\n";
echo "  top: 60%;\n";
echo "}\n";
echo "}\n";
echo "@media only screen and (min-width: 1200px) {\n";
echo ".media {\n";
echo "position:absolute;\n";
echo "  top: 80%;\n";
echo "}\n";
echo "}\n";
echo ".image-wrapper {\n";
echo "  position:relative;\n";
echo "  width: 100%;\n";
echo "  margin: 0px 0px 0px 0px;\n";
//echo "  min-height: 100vh;\n";
echo "}\n";
echo ".spacer {\n";
echo " width: 100%;\n";
echo " height: 400px;\n";
echo "};\n";
echo ".layer {\n";
echo "          position: absolute;\n";
echo "            padding: 20px;\n";
echo "            border-radius: 8px;\n";
echo "}\n";
echo ".orange {\n";
echo "  color: #ff6622;\n";
echo "}\n";
echo ".white {\n";
echo "  color: #ffffff;\n";
echo "}\n";
echo ".noscrollbars {\n";
echo "  overflow-x: visible; overflow-y: visible;\n";
echo "}\n";
echo ".fontsize {\n";
echo "   font-size: 80px;\n";
echo "}\n";
echo ".label_a {\n";
echo "   position: static;\n";
echo "   top: 150px; left: -250px;\n";
echo "}\n";
echo "@media only screen and (max-width: 800px) {\n";
echo ".fontsize {\n";
echo "  font-size: 50px;\n";
echo "}\n";
echo ".label_a {\n";
echo "  visibility: hidden;\n";
echo "}\n";
echo "}\n";
echo "a.link {\n";
echo "   text-decoration: none !important;\n";
echo "   -webkit-box-shadow: none !important;\n";
echo "   box-shadow: none !important;\n";
echo "}\n";
echo ".bl_container {\n";
echo "  display: flex;\n";
echo "  flex: 95%;\n";
echo "  width: 98%;\n";
echo "  flex: 0 0 auto;\n";
echo "  flex-wrap: wrap;\n";
echo "   width: 100%;\n";
echo "    margin: 0 auto;\n";
echo "    padding: 0 15px;\n";
echo "    box-sizing: border-box;\n";
echo "}\n";
echo ".bl_row {\n";
echo "  display: flex;\n";
echo "  flex-direction: row;\n";
echo "  flex-wrap: none;\n";
echo "position: relative;\n";
echo "border-style: solid;\n";
echo "border-width: 2px;\n";
echo "border-radius: 50px;\n";
echo "background-color: #dddddd;\n";
echo "padding: 30px;\n";
echo "margin: 30px;\n";
echo "width: 80%;\n";
echo "}\n";
echo ".bl_column {\n";
echo "display:flex;\n";
echo "  flex-direction: column;\n";
echo "  flex-wrap: none;\n";
echo "  width: 40%;\n";
echo "  flex: 50%;\n";
echo "position: relative;\n";
echo "}\n";
echo "@media (max-width: 1100px) {\n";
echo ".bl_row {\n";
echo "  flex-direction: column;\n";
echo "  flex: 100%;\n";
echo "}\n";
echo ".bl_column {\n";
echo "  width: 80%;\n";
echo "}\n";
echo "}\n";
echo ".bl_item {\n";
echo "display: block;\n";
echo "margin: 30px;\n";
echo "position: relative;\n";
echo "}\n";
echo ".bl_item img {\n";
echo "display: flex; justify-content: center;\n";
echo "margin: 30px;\n";
echo "position: relative;\n";
echo "}\n";
echo "@media (max-width: 600px) {\n";
echo ".bl_item {\n";
echo "  margin: 2px;\n";
echo "}\n";
echo ".bl_item img {\n";
echo "  margin: 2px;\n";
echo "} }\n";
echo ".bl_img {\n";
echo "   width: 400px;";
echo "   border-radius: 10px;\n";
echo "   border-style: solid;\n";
echo "   border-width: 2px;\n";
echo "}\n";
echo ".bl_iframe {\n";
//echo "  background-color: #00ff00;\n";
echo "  width: 800px;\n";
echo "}\n";
echo "@media (max-width: 900px) {\n";
echo ".bl_iframe {\n";
echo "  position: relative;\n";
echo "  left: -80px;\n";
//echo "  background-color: #ff0000;\n";
echo "  width: 480px;\n";
echo "}\n";
echo "}\n";

echo "@media (max-width: 700px) {\n";
echo ".bl_iframe {\n";
echo "  position: relative;\n";
echo "  left: -150px;\n";
//echo "  background-color: #ff0000;\n";
echo "  width: 480px;\n";
echo "}\n";
echo "}\n";
echo "@media (max-width: 600px) {\n";
echo ".bl_img {\n";
echo "   width: 280px;";
echo "}\n";
echo "}\n";
echo ".grid_container {\n";
echo "   display: grid;\n";
echo "   margin: 20px; \n";
echo "    width: 100%;\n";
echo "    margin: 0 auto;\n";
echo "    padding: 0 15px;\n";
echo "    box-sizing: border-box;\n";
echo "}\n";
echo ".img {\n";
echo "border-width: 2px;\n";
echo "border-style: solid;\n";
echo "border-radius: 10px;\n";
echo "background-color: #ffffff;\n";
echo "}\n";
echo "img, video {\n";
echo "    max-width: 100%;\n";
echo "    height: auto;\n";
echo "}\n";

echo ".grid_item {\n";
echo "  display: grid;\n";
echo "   margin: 5px 0px 5px 5px;\n";
echo "  background-color: #aa9988;\n";
echo "border-radius: 30px;\n";
echo "border-width: 2px;\n";
echo "border-style: solid;\n";
echo "}\n";
echo ".grid_elem {\n";
echo "  display: grid;\n";
echo "  grid-auto-flow: column;\n";
echo "   margin: 5px 0px 5px 5px;\n";
echo "}\n";
echo ".grid_item1 {\n";
echo "  display: flex;\n";
echo "  grid-column: 1/2;\n";
echo "   text-align: right;\n";
echo "   justify-content: right;\n";
echo "   text-decoration-line: none;\n";
echo "   color: black;\n";
echo "   padding: 28px 0px 0px 0px;\n";
echo "   z-index: 1;\n";
echo "}\n";
echo ".grid_item1_a {\n";
echo "  display: flex;\n";
echo "  grid-column: 1/3;\n";
echo "   text-align: left;\n";
echo "   justify-content: left;\n";
echo "   text-decoration-line: none;\n";
echo "   color: black;\n";
echo "   padding: 28px 0px 0px 0px;\n";
echo "}\n";
echo "@media only screen and (max-width: 600px) {\n";
echo ".grid_item1 {\n";
echo "  width: 0px;\n";
echo "  display: none;\n";
echo "}\n";
echo ".grid_item3_a {\n";
echo "  width: 0px;\n";
echo "  display: none;\n";
echo "}\n";
echo ".grid_container > div {\n";
echo "   align-items: center;\n";
echo "   align-content: center;\n";
echo "}\n";
echo ".grid_elem > div {\n";
echo "   align-items: center;\n";
echo "   align-content: center;\n";
echo "}\n";
echo ".center {\n";
echo "  margin: auto; width: 150;\n";
echo "}\n";
echo "}\n";

echo ".width320 {\n";
echo "  width: 400px;\n";
echo "}\n";
echo ".width150 {\n";
echo "  width: 150px;\n";
echo "}\n";
echo ".width200 {\n";
echo "  width: 200px;\n";
echo "}\n";
echo ".width620 {\n";
echo "  width: 680px;\n";
echo "}\n";
echo ".height620 {\n";
echo "  height: 680px;\n";
echo "}\n";


echo ".grid_item2 {\n";
echo "  grid-column: 2/3;\n";
echo "   margin: 5px 5px 5px 0px;\n";
echo "   padding: 5px; \n";
echo "}\n";
echo ".grid_item3 {\n";
echo "  display: block;\n";
echo "  grid-column: 3/3;\n";
//echo "   margin: 25px 5px 5px 0px;\n";
echo "   padding: 5px; \n";
echo "   text-align: left;\n";
echo "   justify-content: center;\n";
echo "   justify-items: center;\n";
echo "   text-decoration-line: none;\n";
echo "   color: black;\n";
echo "   height: 75px;\n";
echo "}\n";
echo ".grid_item3_a {\n";
echo "  display: inline;\n";
echo "   position: absolute;\n";
echo "  top: 57px; left: 490px; \n";
echo "  grid-column: 3/3;\n";
//echo "   margin: 25px 5px 5px 0px;\n";
echo "   padding: 5px; \n";
echo "   text-align: left;\n";
echo "   justify-content: left;\n";
echo "   justify-items: left;\n";
echo "   text-decoration-line: none;\n";
echo "   color: black;\n";
echo "   height: 250px;\n";
echo "}\n";
echo "@media only screen and (max-width: 780px) {\n";
echo ".grid_item3 {\n";
echo " width:0px; display:none;\n";
echo "}\n";
echo "}\n";

echo ".grid_item:hover {\n";
echo "   background-color: #ffaa88;\n";
echo "}\n";
echo "@font-face { font-family: \"custom\"; src: url(\"cafe.ttf\"); }\n";
echo ".customfont { font-family: custom; }\n";
echo ".hardshadow {\n";
echo "text-shadow: \n";
echo "                -2px -2px 0 #000,\n";
echo "                2px -2px 0 #000,\n";
echo "                -2px 2px 0 #000,\n";
echo "                2px 2px 0 #000,\n";
echo "                -3px 0 0 #000,\n";
echo "                3px 0 0 #000,\n";
echo "                0 -3px 0 #000,\n";
echo "                0 3px 0 #000;\n";
echo "}\n";
echo ".imgs2 {\n";
echo "  border-radius: 7px;\n";
echo "  border-style: solid;\n";
echo "  border-width: 1px;\n";
echo "}";
echo "</style>\n";

echo "<div style=\"height:50px;\"></div>";

echo "<!-- Begin SF Tag -->";
echo "<div style=\"position: static; margin-left: 27px;\" class=\"sf-root\" data-id=\"3771512\" data-badge=\"light-default\" data-variant-id=\"sf\" style=\"width:125px\">";
echo "<a href=\"https://sourceforge.net/software/product/Meshpage.org/\" target=\"_blank\">Meshpage.org Reviews</a>";
echo "</div>";
echo "<script>(function () {var sc=document.createElement('script');sc.async=true;sc.src='https://b.sf-syn.com/badge_js?sf_id=3771512&variant_id=sf';var p=document.getElementsByTagName('script')[0];p.parentNode.insertBefore(sc, p);})();";
echo "</script>";
echo "<!-- End SF Tag -->";
echo "<footer style=\"position: static; margin-left: 27px;\" class=\"customfont\" id=\"gnomeauthor\">";
echo "*) \"Mesh Garden Gnome\" (<a href=\"https://skfb.ly/D9Fq\">https://skfb.ly/D9Fq</a>) by Seth Berrier is licensed under Creative Commons Attribution (<a href=\"http://creativecommons.org/licenses/by/4.0/\">http://creativecommons.org/licenses/by/4.0/</a>).";
echo "</footer>";

  // COPYRIGHT NOTICE
   echo "<div style=\"height:20px;\"></div>\n";
   echo "<p>\n";
   echo "<div style=\"position: relative;\">\n";
   echo "<div style=\"width: 100%; float:left;\">\n";
   echo "<div class=\"customfont\" style=\"position: static; margin-left: 27px;\"><strong>3D engine &copy; 2013-2025 Tero Pulkkinen, All rights reserved.<br>\n";
echo "Licensed under LGPL/GPL license. See source code at <a href=\"https://github.com/terop2/GameApi\">https://github.com/terop2/GameApi</a>.<br>\n";
echo "meshpage.org" . "&reg; is a registered trademark of Tero Pulkkinen in Tampere.</strong></div>\n";
   echo "</div>\n";
   echo "</div>\n";
   echo "</div>\n";
echo "<p><p><p><p><p><p><p><br><br><br><br><br>\n";

echo "<script>\n";
echo "(function() {\n";
echo "  if (!crossOriginIsolated) console.log(\"MAIN WINDOW not crossorigin isolated\"); else console.log(\"MAIN WINDOW OK\");\n";
echo "})();\n";
echo "</script>\n";
echo "</body>\n";
echo "</html>\n";