
all:
	em++ -std=c++11 -g --embed-file FreeSans.ttf -O2 test.cpp ..\libGameApi.bc -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s USE_SDL_MIXER=1 -s DEMANGLE_SUPPORT=1 -s ALLOW_MEMORY_GROWTH=1 -L.. -L..\objs -I.. -o mini.html