
CROSS_COMPILE=/home/terop/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/
CC = $(CROSS_COMPILE)aarch64-linux-android30-clang++
#armv7a-linux-androideabi30-clang++

ANDROID_HOME = /home/terop/Android/Sdk

ANDROID_SDL = /home/terop/cvs/GameApi/GameApi/androiddeps/SDL2

all:
	@echo "  LD   cmdline/gameapi_cmdline"
	@cp ../libGameApi.la libGameApi.so
	@$(CC) -I$(ANDROID_SDL)/include -I$(ANDROID_SDL)/src -I.. -L$(ANDROID_SDL)/lib -fPIC -shared -DANDROID test.cpp -o libgameapi_cmdline.so -I.. -L. -lGameApi -lSDL2 -lSDL2main -lm -ldl -lGLESv1_CM -lGLESv2 -llog -landroid
	@mkdir -p src/main/jniLibs/arm64-v8a
	@mkdir -p src/main/jniLibs/armeabi-v7a
	@cp libgameapi_cmdline.so src/main/jniLibs/arm64-v8a/
	@cp libGameApi.so src/main/jniLibs/arm64-v8a/
	@cp ../androiddeps/SDL/build/.libs/libSDL2-2.0.so src/main/jniLibs/arm64-v8a/libSDL2-2.0.so
	@cp ../androiddeps/freetype-2.13.3/build/.libs/libfreetype.so src/main/jniLibs/arm64-v8a/libfreetype.so
	@mkdir -p src/main/java/org/libsdl/app
	#@cat ../androiddeps/SDL/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java |sed s/\"SDL2\",/\"SDL2\",\"freetype\",\"GameApi\",\"gameapi_cmdline\"/ >src/main/java/org/libsdl/app/SDLActivity.java
	@mkdir -p res/mipmap-hdpi
	@mkdir -p res/mipmap-mdpi
	@mkdir -p res/mipmap-xhdpi
	@mkdir -p res/mipmap-xxhdpi
	@mkdir -p assets
	@mkdir -p lib/arm64-v8a
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30/libm.so lib/arm64-v8a/
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30/libdl.so lib/arm64-v8a/
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30/libGLESv1_CM.so lib/arm64-v8a/
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30/libGLESv2.so lib/arm64-v8a/
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30/liblog.so lib/arm64-v8a/
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30/libandroid.so lib/arm64-v8a/
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30/libc.so lib/arm64-v8a/
	@cp $(ANDROID_HOME)/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so lib/arm64-v8a/
	@cp libGameApi.so lib/arm64-v8a/
	@cp ../androiddeps/SDL/build/.libs/libSDL2-2.0.so lib/arm64-v8a/libSDL2.so
	@cp ../androiddeps/freetype-2.13.3/build/.libs/libfreetype.so lib/arm64-v8a/
	@cp libgameapi_cmdline.so lib/arm64-v8a/
	@cp script.txt assets/
	@javac -source 8 -target 8 -d classes -bootclasspath $(ANDROID_HOME)/platforms/android-33/android.jar src/main/java/org/libsdl/app/SDLActivity.java src/main/java/org/libsdl/app/SDLSurface.java src/main/java/org/libsdl/app/SDLAudioManager.java src/main/java/org/libsdl/app/SDLControllerManager.java src/main/java/org/libsdl/app/SDL.java src/main/java/org/libsdl/app/HIDDeviceManager.java src/main/java/org/libsdl/app/HIDDevice.java src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java src/main/java/org/libsdl/app/HIDDeviceUSB.java src/org/meshpage/gameapi/R.java src/org/libsdl/app/R.java
	@d8 --lib /home/terop/Android/Sdk/platforms/android-33/android.jar classes/org/libsdl/app/SDLActivity$$SDLCommandHandler.class classes/org/libsdl/app/SDLSurface.class classes/org/libsdl/app/SDLAudioManager.class classes/org/libsdl/app/SDLControllerManager.class classes/org/libsdl/app/HIDDevice.class classes/org/libsdl/app/HIDDeviceBLESteamController.class classes/org/libsdl/app/HIDDeviceUSB.class --output .
	@$(ANDROID_HOME)/build-tools/33.0.0/aapt2 compile --dir res/ -o compiled_resources/
	@$(ANDROID_HOME)/build-tools/33.0.0/aapt2 link -o unsigned.apk -I $(ANDROID_HOME)/platforms/android-33/android.jar --java src --shared-lib --manifest AndroidManifest.xml -A assets compiled_resources/*.flat
	@zip -r unsigned.apk lib/arm64-v8a/libm.so
	@zip -r unsigned.apk lib/arm64-v8a/libdl.so
	@zip -r unsigned.apk lib/arm64-v8a/libGLESv1_CM.so
	@zip -r unsigned.apk lib/arm64-v8a/libGLESv2.so
	@zip -r unsigned.apk lib/arm64-v8a/liblog.so
	@zip -r unsigned.apk lib/arm64-v8a/libandroid.so
	@zip -r unsigned.apk lib/arm64-v8a/libc.so
	@zip -r unsigned.apk lib/arm64-v8a/libc++_shared.so
	@zip -r unsigned.apk lib/arm64-v8a/libgameapi_cmdline.so
	@zip -r unsigned.apk lib/arm64-v8a/libfreetype.so
	@zip -r unsigned.apk lib/arm64-v8a/libGameApi.so
	@zip -r unsigned.apk lib/arm64-v8a/libSDL2.so
	@zip -r unsigned.apk res/values/strings.xml
	@zip -r unsigned.apk src/org/meshpage/gameapi/R.java
	@zip -r unsigned.apk src/org/libsdl/app/R.java
	@zip -r unsigned.apk src/main/java/org/libsdl/app/SDLActivity.java
	@zip -r unsigned.apk classes.dex
	@(cd classes;zip -r ../unsigned.apk org/libsdl/app/SDLActivity$$SDLCommandHandler.class)
	@(cd classes;zip -r ../unsigned.apk org/libsdl/app/SDLSurface.class)
	@(cd classes;zip -r ../unsigned.apk org/libsdl/app/SDLAudioManager.class)
	@(cd classes;zip -r ../unsigned.apk org/libsdl/app/SDLControllerManager.class)
	@(cd classes;zip -r ../unsigned.apk org/libsdl/app/HIDDevice.class)
	@(cd classes;zip -r ../unsigned.apk org/libsdl/app/HIDDeviceBLESteamController.class)
	@(cd classes;zip -r ../unsigned.apk org/libsdl/app/HIDDeviceUSB.class)

	@$(ANDROID_HOME)/build-tools/33.0.0/zipalign -v 4 unsigned.apk aligned.apk
	@$(ANDROID_HOME)/build-tools/33.0.0/apksigner sign --ks debug.keystore aligned.apk
	@mv aligned.apk gameapi_cmdline.apk
	@$(ANDROID_HOME)/cmdline-tools/latest/bin/apkanalyzer apk summary gameapi_cmdline.apk