
all:
	@echo "  LD   cmdline/gameapi_cmdline"
	@g++ -m64 test.cpp -o gameapi_cmdline -I.. -L.. -lGameApi
	@echo "  LD   cmdline/gameapi_cmdline.small"
	@g++ -m64 test.cpp -o gameapi_cmdline.small -I.. -L.. -lGameApi_small
