# 
# Copyright (C) 2009 Tero Pulkkinen
# Released under LGPL License.
#
# This file is part of Polygon.
#
# Polygon is free software: you can redistribute it and/or modify
# it under the terms of the GNU Library General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Polygon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#



STEAM_ENABLE ?= no
STEAM_DEPLOY_ENABLE ?= no
STEAM_SDK_PATH ?= c:\users\terop\cvs\steam\sdk
ifeq ($(STEAM_ENABLE),yes)
STEAM_PATH=$(STEAM_SDK_PATH)
STEAM_NAME=$(STEAM_PATH)/redistributable_bin/win64/steam_api64.dll
STEAM_H_TEST=$(STEAM_PATH)/public/steam/steam_api.h
ifeq ($(STEAM_DEPLOY_ENABLE),yes)
STEAM_CFLAGS=-DSTEAM -DSTEAM_DEPLOY -I$(STEAM_PATH)/public
else
STEAM_CFLAGS=-DSTEAM -I$(STEAM_PATH)/public
endif
STEAM_LIBS=-L$(STEAM_PATH)\redistributable_bin\win64 $(STEAM_PATH)\redistributable_bin\win64\steam_api64.dll
else
STEAM_PATH=
STEAM_NAME=
STEAM_H_TEST=
STEAM_CFLAGS=
STEAM_LIBS=
endif



CFiles_dep= VectorTools.cc Buffer.cc  GameApi_low.cc GameApi_low_stub.cc GameApi_dep_add_find.cc GameApi_dep_env.cc Shader.cc VertexArray.cc  GameApi_dep_arr_render.cc GameApi_dep_store.cc

CFiles_bm = 
CFiles_pl =   
CFiles_ml = 
CFiles_mt =  
CFiles=	GameApi2.cc GameApi_webcam.cc GameApi_diag.cc GameApi_gltf.cc Pieces.cc Map.cc Effect.cc GameApi_bm.cc GameApi_cmd_bitmap.cc GameApi_cmd_bbitmap.cc \
	GameApi_gui.cc Intersect.cc Bitmap.cc Effect2.cc  VolumeObjects.cc \
	 Graph.cc State.cc Web.cc Triangle.cc \
	 Event.cc  ObjectCreator.cc Coordinates.cc \
	 Functions.cc Widgets.cc Category.cc \
	 GameApiTest.cc Games.cc HierarchyObject.cc Physics.cc \
          GameApi_ev.cc Tree.cc  IntersectObject.cc GameApi_an.cc  GameApi_co.cc GameApi_dr.cc Plane.cc    Game.cc  GameApi_f.cc GameApi_fn.cc \
	FreeType.cc FreeType2.cc StateChange.cc DistanceObject.cc GameRunner.cc \
	 GameApi_ex.cc  GameApi_fbo.cc GameApi_phy.cc \
	 GameApi_integrator.cc Editor.cc   ShaderExpr.cc Font.cc FontEditor.cc GameApi_pla.cc  GameApi_pt.cc \
	GameApi_fnt.cc GameApi_gr.cc \
	GameApi_pl.cc GameApi_cmd_polygon2.cc GameApi_cmd_polygon.cc GameApiTest2.cc  Serialize.cc KeyFrameEditor.cc Parser.cc GameApi_imp.cc GameApi_plane.cc \
	GameApi_lay.cc  GameApi_main.cc GameApi_cmd_mainloop.cc \
	GameApi_li.cc  GameApi_mx.cc GameApi_pc.cc \
	 \
	GameApi_pts.cc GameApi_sh.cc GameApi_shm.cc GameApi_sm.cc \
        GameApi_spa.cc GameApi_sp.cc GameApi_st.cc GameApi_su.cc \
        GameApi_tex.cc GameApi_tr.cc GameApi_trk.cc GameApi_tx.cc \
        GameApi_vbo.cc GameApi_ve.cc GameApi_vo.cc GameApi_wmod.cc \
        GameApi_wv.cc GameApi_vx.cc GameApi_cut.cc GameApi_in.cc \
	 GameApi_vr.cc \
 	GameApi_qt.cc GameApi_low_egl.cc escapi.cc \
	GameApi_cmd_move.cc GameApi.cc GameApi_cmd_material.cc \
	       GameApi_cmd_pdfield.cc \
	        GameApi_cmd_point.cc \
	GameApi_cmd_booleanops.cc    GameApi_cmd_points.cc \
	GameApi_cmd_cvolume.cc        \
	GameApi_cmd_fbitmap.cc        \
	GameApi_cmd_font.cc          GameApi_cmd_framebuffer.cc \
	GameApi_cmd_texture.cc GameApi_cmd_fvolume.cc \
	GameApi_cmd_lines.cc         GameApi_cmd_vector.cc \
	      GameApi_cmd_volume.cc \
	      GameApi_cmd_waveform.cc GameApi_cmd_shader.cc \
	GameApi_cmd.cc cpushader.cc \
draco/attributes/attribute_octahedron_transform.cc    draco/attributes/geometry_attribute.cc \
draco/attributes/attribute_quantization_transform.cc  draco/attributes/point_attribute.cc \
draco/attributes/attribute_transform.cc \
draco/compression/decode.cc                          draco/compression/encode.cc         \
draco/compression/draco_compression_options.cc       draco/compression/expert_encode.cc \
draco/compression/attributes/attributes_decoder.cc \
draco/compression/attributes/attributes_encoder.cc \
draco/compression/attributes/sequential_attribute_decoder.cc \
draco/compression/attributes/sequential_attribute_decoders_controller.cc \
draco/compression/attributes/sequential_attribute_encoder.cc \
draco/compression/attributes/sequential_attribute_encoders_controller.cc \
draco/compression/attributes/sequential_integer_attribute_decoder.cc \
draco/compression/attributes/sequential_integer_attribute_encoder.cc \
draco/compression/attributes/sequential_normal_attribute_decoder.cc \
draco/compression/attributes/sequential_normal_attribute_encoder.cc \
draco/compression/attributes/sequential_quantization_attribute_decoder.cc \
draco/compression/attributes/sequential_quantization_attribute_encoder.cc \
draco/compression/attributes/prediction_schemes/prediction_scheme_encoder_factory.cc \
draco/compression/bit_coders/adaptive_rans_bit_decoder.cc  draco/compression/bit_coders/direct_bit_encoder.cc   \
draco/compression/bit_coders/adaptive_rans_bit_encoder.cc  draco/compression/bit_coders/rans_bit_decoder.cc    draco/compression/bit_coders/symbol_bit_decoder.cc \
draco/compression/bit_coders/direct_bit_decoder.cc         draco/compression/bit_coders/rans_bit_encoder.cc    draco/compression/bit_coders/symbol_bit_encoder.cc \
draco/compression/entropy/shannon_entropy.cc       draco/compression/entropy/symbol_encoding.cc \
draco/compression/entropy/symbol_decoding.cc \
draco/compression/mesh/mesh_decoder.cc                \
draco/compression/mesh/mesh_edgebreaker_decoder.cc       draco/compression/mesh/mesh_encoder.cc \
draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc  \
draco/compression/mesh/mesh_edgebreaker_encoder.cc       draco/compression/mesh/mesh_sequential_decoder.cc \
draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc  draco/compression/mesh/mesh_sequential_encoder.cc \
draco/compression/point_cloud/point_cloud_decoder.cc        \
draco/compression/point_cloud/point_cloud_encoder.cc \
draco/compression/point_cloud/point_cloud_sequential_decoder.cc \
draco/compression/point_cloud/point_cloud_kd_tree_decoder.cc \
draco/compression/point_cloud/point_cloud_sequential_encoder.cc \
draco/compression/point_cloud/point_cloud_kd_tree_encoder.cc \
draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.cc  draco/compression/point_cloud/algorithms/float_points_tree_encoder.cc \
draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_encoder.cc  draco/compression/point_cloud/algorithms/integer_points_kd_tree_decoder.cc \
draco/compression/point_cloud/algorithms/float_points_tree_decoder.cc               draco/compression/point_cloud/algorithms/integer_points_kd_tree_encoder.cc \
draco/core/bit_utils.cc               draco/core/divide.cc            draco/core/options.cc \
draco/core/bounding_box.cc            draco/core/quantization_utils.cc \
draco/core/draco_types.cc      \
draco/core/cycle_timer.cc             draco/core/encoder_buffer.cc    draco/core/status.cc \
draco/core/data_buffer.cc             draco/core/hash_utils.cc     \
draco/core/decoder_buffer.cc       \
draco/mesh/corner_table.cc                 draco/mesh/mesh_misc_functions.cc    draco/mesh/mesh_splitter.cc \
draco/mesh/mesh_are_equivalent.cc          draco/mesh/mesh_stripifier.cc \
draco/mesh/mesh_attribute_corner_table.cc  \
draco/mesh/mesh.cc                         draco/mesh/mesh_utils.cc \
draco/mesh/mesh_cleanup.cc                \
draco/mesh/triangle_soup_mesh_builder.cc \
draco/mesh/mesh_features.cc  \
draco/point_cloud/point_cloud_builder.cc       draco/point_cloud/point_cloud.cc \
draco/compression/attributes/kd_tree_attributes_decoder.cc \
draco/compression/attributes/kd_tree_attributes_encoder.cc \
draco/metadata/geometry_metadata.cc  draco/metadata/metadata_encoder.cc       draco/metadata/property_table.cc     \
draco/metadata/metadata.cc     \
draco/metadata/metadata_decoder.cc          draco/metadata/structural_metadata.cc \


WARN = -Wno-return-type -Wno-unused-function -Wno-sign-compare -Wno-reorder -Wno-unused-variable -Wno-cpp  -Wno-unused-but-set-variable -Wno-misleading-indentation -Wno-bool-compare

CFiles2 = Main.cc

CFiles_examples = GameApiTest3.cc GameApiTest4.cc GameApiWorld.cc GameApiTest5.cc GameApiTest6.cc GameApiTest7.cc GameApiTest8.cc GameApiTest9.cc GameApiTestA.cc
CFiles2_examples = ExampleMain.cc
Subdirs = 
#module1

OFiles = $(patsubst %.cc,objs/%.o,$(CFiles) $(CFiles2))
OFiles_bm = $(patsubst %.cc,objs/%.o,$(CFiles_bm))
OFiles_pl = $(patsubst %.cc,objs/%.o,$(CFiles_pl))
OFiles_ml = $(patsubst %.cc,objs/%.o,$(CFiles_ml))
OFiles_mt = $(patsubst %.cc,objs/%.o,$(CFiles_mt))
O2Files = $(patsubst %.cc,objs/%.obj,$(CFiles) $(CFiles2))
OFiles_dep = $(patsubst %.cc,objs/%.o,$(CFiles_dep))
O2Files_dep = $(patsubst %.cc,objs/%.obj,$(CFiles_dep))
DFiles = $(patsubst %.cc,objs/%.d,$(CFiles) $(CFiles2)) 
D2Files = $(patsubst %.cc,objs/%.d2,$(CFiles) $(CFiles2)) 
D3Files = $(patsubst %.cc,objs/%.d3,$(CFiles_dep))
HFiles = $(patsubst %.cc,%.hh,$(CFiles))
GCHFiles = $(patsubst %.cc,objs/%.hh.gch,$(CFiles))
GCH2Files = $(patsubst %.cc,objs/%.hh.gch2,$(CFiles))
Subdirsx = $(patsubst %,%build,$(Subdirs))

OFiles_examples = $(patsubst %.cc,objs/%.o,$(CFiles_examples) $(CFiles2_examples))
O2Files_examples = $(patsubst %.cc,objs/%.obj,$(CFiles_examples) $(CFiles2_examples))
DFiles_examples = $(patsubst %.cc,objs/%.d,$(CFiles_examples) $(CFiles2_examples)) 
D2Files_examples = $(patsubst %.cc,objs/%.d2,$(CFiles_examples) $(CFiles2_examples)) 
HFiles_examples = $(patsubst %.cc,%.hh,$(CFiles_examples))
GCHFiles_examples = $(patsubst %.cc,objs/%.hh.gch,$(CFiles_examples))
GCH2Files_examples = $(patsubst %.cc,objs/%.hh.gch2,$(CFiles_examples))

CVSPATH=c:\users\terop\cvs

LIBWIN = $(CVSPATH)\SDL2-2.0.22\x86_64-w64-mingw32\bin
LIB2WIN = editor
LIB3WIN = $(CVSPATH)\glew\glew-2.1.0\bin\Release\Win32
LIB4WIN = e:\cvs
LIB5WIN = $(CVSPATH)\sdl2_image\SDL2_image-2.0.5\x86_64-w64-mingw32\lib
LIB6WIN = d:\cvs\glew-1.10.0\lib
LIB7WIN = $(CVSPATH)\pthread
LIB8WIN = $(CVSPATH)\sdl2_mixer\SDL2_mixer-2.0.4\x86_64-w64-mingw32\lib
LIB9WIN = openvr
#LIB10WIN = chai\ChaiScript-6.1.0
INC1WIN = $(CVSPATH)\SDL2-2.0.22\x86_64-w64-mingw32\include\sdl2
INC2WIN = $(CVSPATH)\glew\glew-2.1.0\glew-2.1.0\include
INC3WIN = $(CVSPATH)\sdl2_image\SDL2_image-2.0.5/x86_64-w64-mingw32/include\sdl2
INC4WIN = $(CVSPATH)\SDL2-2.0.22\x86_64-w64-mingw32\include\SDL2
INC5WIN = $(CVSPATH)\gameapi_libs\gameapi_libs\freetype\include
INC6WIN = $(CVSPATH)\gameapi_libs\gameapi_libs\freetype\include\freetype2
INC7WIN = $(CVSPATH)\pthread
INC8WIN = $(CVSPATH)\sdl2_mixer\SDL2_mixer-2.0.4\x86_64-w64-mingw32/include/sdl2
#INC10WIN = chai\ChaiScript-6.1.0\include

#  -fPIC -ftrack-macro-expansion=0 -fno-var-tracking-assignments

CCFLAGS = $(STEAM_CFLAGS) -fext-numeric-literals -fno-var-tracking-assignments -ftrack-macro-expansion=0 -fPIC -DGAMEAPI_EXPORTS -fvisibility=hidden -I. -m64 -O2 -DWINDOWS -std=c++20 -Wall -I./objs -I/usr/include/freetype2 -DHAVE_STRUCT_TIMESPEC  -Iescapi -Ichai/ChaiScript-6.1.0/include -Wa,-mbig-obj -Ichai/ChaiScript-6.1.0/include $(WARN) -I./hssynth2/midiplay/midifile/include -I./hssynth2/synthlib -pthread
CC2FLAGS = $(STEAM_CFLAGS) -fext-numeric-literals -fPIC -ftrack-macro-expansion=0 -fno-var-tracking-assignments -DGAMEAPI_EXPORTS -fvisibility=hidden -I. -m64 -O2 -DWINDOWS -std=c++20 -Wall -I./objs -I$(INC1WIN) -I$(INC2WIN) -I$(INC3WIN) -I$(INC4WIN) -I$(INC5WIN) -I$(INC6WIN) -I$(INC7WIN) -I$(INC8WIN) -DGLEW_STATIC -DHAVE_STRUCT_TIMESPEC -U__STRICT_ANSI__ -Iholoplay -Lholoplay  -Iescapi -Ichai/ChaiScript-6.1.0/include -Wa,-mbig-obj -Ichai/ChaiScript-6.1.0/include $(WARN) -I./hssynth2/midiplay/midifile/include -I./hssynth2/synthlib -pthread
#`pkg-config gtkmm-2.4 --cflags`


default: glew.o libGameApi.dll  

touch_all: GameApi_gui.cc
	touch GameApi_gui.cc
	touch GameApi_gui_1_1.cc
	touch GameApi_gui_2_1.cc
	touch GameApi_gui_3_1.cc
	touch GameApi_gui_1_2.cc
	touch GameApi_gui_2_2.cc
	touch GameApi_gui_3_2.cc
	touch GameApi_gui_1_3.cc
	touch GameApi_gui_2_3.cc
	touch GameApi_gui_3_3.cc

touch_gui:
	touch GameApi_gui_1_1.cc
touch_polydistfield:
	touch GameApi_gui_2_1.cc
touch_waveform:
	touch GameApi_gui_2_3.cc
touch_blocker:
	touch GameApi_gui_2_2.cc
touch_mainloop:
	touch GameApi_gui_2_2.cc
touch_texture:
	touch GameApi_gui_1_2.cc
touch_volume:
	touch GameApi_gui_1_2.cc
touch_floatvolume:
	touch GameApi_gui_1_2.cc
touch_colorvolume:
	touch GameApi_gui_1_2.cc
touch_vector:
	touch GameApi_gui_1_2.cc
touch_point:
	touch GameApi_gui_1_2.cc
touch_font:
	touch GameApi_gui_1_2.cc
touch_move:
	touch GameApi_gui_2_1.cc
touch_polygon:
	touch GameApi_gui_2_2.cc
	touch GameApi_gui_2_3.cc
touch_polygon1:
	touch GameApi_gui_2_2.cc
touch_polygon2:
	touch GameApi_gui_2_3.cc
touch_shadermodule:
	touch GameApi_gui_2_2.cc
touch_framebuffermodule:
	touch GameApi_gui_2_1.cc
touch_booleanops:
	touch GameApi_gui_3_3.cc
touch_lines:
	touch GameApi_gui_3_1.cc
touch_points:
	touch GameApi_gui_3_2.cc
touch_floatbitmap:
	touch GameApi_gui_3_3.cc
touch_boolbitmap:
	touch GameApi_gui_3_1.cc
touch_bitmap:
	touch GameApi_gui_3_2.cc

all: libGameApi.so libGameApi.dll install main

examples: main

main: $(GCHFiles_examples) $(OFiles_examples) Makefile GameApi.hh libGameApi.so
	@echo g++ main
	@g++ $(OFiles_examples) -std=c++17 -o main -L. -lGameApi -lGL -lm -lstdc++

main.exe: $(GCHFiles_examples) $(O2Files_examples) Makefile GameApi.hh libGameApi.dll
	@echo mingw main.exe
	@$(CCWIN) -m64 $(O2Files_examples) -o main.exe -L. -lGameApi -lopengl32 -lm -lstdc++ 


#`pkg-config gtkmm-2.4 --libs` 

#libGameDep.dll: $(O2Files_dep) Makefile.win32 glew.o
#	@echo mingw libGameDep.dll
#	@g++ -DGAMEAPI_EXPORTS -m64 -Wa,-mbig-obj -std=c++17 -L$(LIBWIN) -L$(LIB2WIN) -L$(LIB3WIN) -L$(LIB4WIN) -L$(LIB5WIN) -L$(LIB6WIN) -L$(LIB7WIN) -L$(LIB8WIN) -L$(LIB9WIN) -shared $(O2Files_dep) -DGLEW_STATIC glew.o -o libGameDep.dll -lSDL2 -lSDL2_image -lSDL2_mixer -lfreetype-6 -lstdc++ -lgcc -lwsock32 -lopengl32 -lpthreadgc2 -Lopenvr -lopenvr_api -pthread

#-Wl,--reduce-memory-overheads

libGameApi.dll: $(O2Files_dep) $(O2Files) Makefile.win32 glew.o libGameDep.dll
	@echo mingw libGameApi.dll
	@g++ -DGAMEAPI_EXPORTS -m64 -Wa,-mbig-obj -L. -L$(LIBWIN) -L$(LIB2WIN) -L$(LIB3WIN) -L$(LIB4WIN) -L$(LIB5WIN) -L$(LIB6WIN) -L$(LIB7WIN) -L$(LIB8WIN) -L$(LIB9WIN) -shared $(O2Files_dep) $(O2Files) glew.o -DGLEW_STATIC -o libGameApi.dll holoplay/HoloPlayAPI.lib -lSDL2 -lSDL2_image -lSDL2_mixer -lfreetype-6 -lstdc++ -lgcc -lwsock32 -lopengl32 -Lopenvr -lopenvr_api -lpthreadgc2 -Wl,--out-implib,libGameApi.a -lole32 -levr -lpropsys -lmfplat -lmfreadwrite -lmf -lshlwapi -luuid $(STEAM_LIBS)


#-L./hssynth2/synthlib -lsynthlib -L./hssynth2/midiplay/midifile -lmidifile
#-lchaiscript_stdlib-6.1.0

#	@strip libGameApi.dll

subdirs: $(Subdirs)

$(Subdirs):
	$(MAKE) -C $@

.PHONY: subdirs $(Subdirs)

ctags: TAGS

TAGS: $(CFiles)
	etags -o TAGS -l c++ $(CFiles)

CC = g++
CCWIN = g++
RM = "d:\cvs\gnumake\bin\rm.exe"
SED = "sed.exe"

$(DFiles): objs/%.d: %.cc
	@echo Deps $< -o $@
	@gcc -M -DDEPS $(CCFLAGS) $(CC2FLAGS) $< \
	|$(SED) "s,\($*\)\.o[ :]*,objs/\1.o $@ : ,g" > $@

$(D2Files): objs/%.d2: %.cc    
	@echo Deps $< -o $@
	@$(CCWIN) -DDEPS -M $(CCFLAGS) $(CC2FLAGS) $< \
	|$(SED) "s,\($*\)\.obj[ :]*,objs/\1.obj $@ : ,g" > $@

$(D3Files): objs/%.d3: %.cc    
	@echo Deps $< -o $@
	@$(CCWIN) -DDEPS -M $(CCFLAGS) $(CC2FLAGS) $< \
	|$(SED) "s,\($*\)\.obj[ :]*,objs/\1.obj $@ : ,g" > $@

$(OFiles): objs/%.o : %.cc
	@echo g++ $< -o $@
	@$(CC) -DDEFINE_ALL -std=c++20 -c $(CCFLAGS) $< -o $@

$(OFiles_bm): objs/%.o : %.cc
	@echo g++ $< -o $@
	@$(CC) -DDEFINE_ALL -std=c++20 -c $(CC2FLAGS) $< -o $@

$(OFiles_ml): objs/%.o : %.cc
	@echo g++ $< -o $@
	@$(CC) -DDEFINE_ALL -std=c++20 -c $(CC2FLAGS) $< -o $@

$(OFiles_pl): objs/%.o : %.cc
	@echo g++ $< -o $@
	@$(CC) -DDEFINE_ALL -std=c++20 -c $(CC2FLAGS) $< -o $@

$(OFiles_mt): objs/%.o : %.cc
	@echo g++ $< -o $@
	@$(CC) -DDEFINE_ALL -std=c++20 -c $(CC2FLAGS) $< -o $@



$(O2Files): objs/%.obj : %.cc
	@echo mingw $<
	@$(CCWIN) -DDEFINE_ALL -c $(CC2FLAGS) $< -o $@

$(O2Files_dep): objs/%.obj : %.cc
	@echo mingw $<
	@$(CCWIN) -DDEFINE_ALL -c $(CC2FLAGS) $< -o $@

glew.o:
	$(CCWIN) -c $(CC2FLAGS) c:\users\terop\cvs\glew\glew-2.1.0\glew-2.1.0\src\glew.c -o glew.o


$(OFiles_examples): objs/%.o : %.cc GameApi.hh
	@$(CC) -std=c++17 -c -I. $(CCFLAGS) $< -o $@ 

$(O2Files_examples): objs/%.obj : %.cc GameApi.hh
	@echo mingw $<
	@$(CCWIN) -std=c++17 -c -I. $(CC2FLAGS) $< -o $@ 


$(GCHFiles): objs/%.hh.gch : %.hh
	@$(CC) $(CCFLAGS) -std=c++20 -x c++-header $< -o $@ 

$(GCH2Files): objs/%.hh.gch2 : %.hh
	@echo mingw $<
	@$(CCWIN) $(CC2FLAGS) -x c++-header $< -o $@ 

$(GCHFiles_examples): objs/%.hh.gch : %.hh GameApi.hh
	@$(CC) $(CCFLAGS) -std=c++20 -I. -x c++-header $< -o $@ 

clean:
	del objs\*.o
	del objs\*.obj
	del objs\*.gch
	del objs\*.gch2
	del glew.o
	@echo Clean.






#-include $(DFiles)
-include $(D2Files)
-include $(D3Files)
#-include $(DFiles_examples)
#-include $(D2Files_examples)
