#!/bin/bash

cp /usr/bin/cat editor/builder/GameApiBuilder/
cp /usr/bin/cp editor/builder/GameApiBuilder/
cp /usr/bin/pwd editor/builder/GameApiBuilder/
cp /usr/bin/stdbuf editor/builder/GameApiBuilder/
cp /usr/bin/unzip editor/builder/GameApiBuilder/
cp /usr/bin/zip editor/builder/GameApiBuilder/
cp /usr/bin/mv editor/builder/GameApiBuilder/
cp /usr/bin/curl editor/builder/GameApiBuilder/

cp /usr/lib/x86_64-linux-gnu/libcurl.so.4 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libz.so.1 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libc.so.6 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libidn2.so.0 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/librtmp.so.1 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libldap.so.2 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/liblber.so.2 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libssh2.so.1 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libpsl.so.5 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libssl.so.3 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libcrypto.so.3 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libzstd.so.1 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libunistring.so.5 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libgnutls.so.30 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libhogweed.so.6 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libnettle.so.8 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libgmp.so.10 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libsasl2.so.2 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libkrb5.so.3 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libcom_err.so.2 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libtasn1.so.6 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libkeyutils.so.1 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libresolv.so.2 editor/builder/GameApiBuilder/libs/
cp /usr/lib/x86_64-linux-gnu/libffi.so.8 editor/builder/GameApiBuilder/libs/
