
all:
	g++ -std=c++11 parser.cc -o parser.exe
	g++ -std=c++11 -DWINDOWS file_gen.cc -o file_gen.exe
	@echo Usage: ./file_gen.exe https://www.meshpage.org/mesh.php?id=GVILK@963
	@echo Usage: make compile
	
compile:
	g++ -L.. -I.. -DWINDOWS -DOUTPUT -std=c++11 output.cpp -o output.exe -lGameDep