
all:
	g++ -std=c++11 parser.cc -o parser.exe
	g++ -std=c++11 -DWINDOWS file_gen.cc -o file_gen.exe
	@echo Usage: ./file_gen.exe https://www.meshpage.org/mesh.php?id=GVILK@963
	@echo Usage: make compile

dir = ../
files = $(dir)VectorTools.cc $(dir)Shader.cc $(dir)Main.cc $(dir)VertexArray.cc
	
compile:
	g++ -L.. -I.. -Id:\cvs\glew-1.10.0/include -DWINDOWS -DOUTPUT -std=c++11 output.cpp -o output.exe -lGameDep $(files)

exe:
	(cd ..;cd editor; ../parser2/output.exe)
