
all:
	em++ -std=c++11 -g -O2 test.cpp ..\libGameApi.bc -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s DEMANGLE_SUPPORT=1 -s USE_OGG=1 -s USE_VORBIS=1 -s ASM_JS=1 -s ALLOW_MEMORY_GROWTH=1 -L.. -L..\objs -I.. -o ld35.html --embed-file test.tri --embed-file bee.ogg --embed-file logo.ppm