add_test( [==[compiled.C++11 Lambdas Can Be Registered]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[C++11 Lambdas Can Be Registered]==])
set_tests_properties( [==[compiled.C++11 Lambdas Can Be Registered]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Dynamic_Object attributes can be shared with C++]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Dynamic_Object attributes can be shared with C++]==])
set_tests_properties( [==[compiled.Dynamic_Object attributes can be shared with C++]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Function objects can be created from chaiscript functions]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Function objects can be created from chaiscript functions]==])
set_tests_properties( [==[compiled.Function objects can be created from chaiscript functions]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.ChaiScript can be created and destroyed on heap]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[ChaiScript can be created and destroyed on heap]==])
set_tests_properties( [==[compiled.ChaiScript can be created and destroyed on heap]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test automatic arithmetic conversions]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test automatic arithmetic conversions]==])
set_tests_properties( [==[compiled.Test automatic arithmetic conversions]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Generic exception handling with C++]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Generic exception handling with C++]==])
set_tests_properties( [==[compiled.Generic exception handling with C++]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Throw an int]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Throw an int]==])
set_tests_properties( [==[compiled.Throw an int]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Throw int or double]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Throw int or double]==])
set_tests_properties( [==[compiled.Throw int or double]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Throw a runtime_error]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Throw a runtime_error]==])
set_tests_properties( [==[compiled.Throw a runtime_error]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Throw unhandled type]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Throw unhandled type]==])
set_tests_properties( [==[compiled.Throw unhandled type]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.No unexpected exceptions leak]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[No unexpected exceptions leak]==])
set_tests_properties( [==[compiled.No unexpected exceptions leak]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Function ordering]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Function ordering]==])
set_tests_properties( [==[compiled.Function ordering]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Functor cast]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Functor cast]==])
set_tests_properties( [==[compiled.Functor cast]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Non-ASCII characters in the middle of string]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Non-ASCII characters in the middle of string]==])
set_tests_properties( [==[compiled.Non-ASCII characters in the middle of string]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Non-ASCII characters in the beginning of string]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Non-ASCII characters in the beginning of string]==])
set_tests_properties( [==[compiled.Non-ASCII characters in the beginning of string]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Non-ASCII characters in the end of string]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Non-ASCII characters in the end of string]==])
set_tests_properties( [==[compiled.Non-ASCII characters in the end of string]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.BOM in string]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[BOM in string]==])
set_tests_properties( [==[compiled.BOM in string]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Set and restore chai state]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Set and restore chai state]==])
set_tests_properties( [==[compiled.Set and restore chai state]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Short comparison with int]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Short comparison with int]==])
set_tests_properties( [==[compiled.Short comparison with int]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test lookup of type names]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test lookup of type names]==])
set_tests_properties( [==[compiled.Test lookup of type names]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Simultaneous ChaiScript tests]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Simultaneous ChaiScript tests]==])
set_tests_properties( [==[compiled.Simultaneous ChaiScript tests]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Utility_Test utility class wrapper]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Utility_Test utility class wrapper]==])
set_tests_properties( [==[compiled.Utility_Test utility class wrapper]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Utility_Test utility class wrapper for enum]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Utility_Test utility class wrapper for enum]==])
set_tests_properties( [==[compiled.Utility_Test utility class wrapper for enum]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Object copy counts]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Object copy counts]==])
set_tests_properties( [==[compiled.Object copy counts]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Object lifetime tests]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Object lifetime tests]==])
set_tests_properties( [==[compiled.Object lifetime tests]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Object lifetime test 2]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Object lifetime test 2]==])
set_tests_properties( [==[compiled.Object lifetime test 2]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test Derived->Base with non-polymorphic classes]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test Derived->Base with non-polymorphic classes]==])
set_tests_properties( [==[compiled.Test Derived->Base with non-polymorphic classes]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Variable Scope When Calling From C++]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Variable Scope When Calling From C++]==])
set_tests_properties( [==[compiled.Variable Scope When Calling From C++]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Variable Scope When Calling From C++ 2]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Variable Scope When Calling From C++ 2]==])
set_tests_properties( [==[compiled.Variable Scope When Calling From C++ 2]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test long long dispatch]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test long long dispatch]==])
set_tests_properties( [==[compiled.Test long long dispatch]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Return of converted type from script]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Return of converted type from script]==])
set_tests_properties( [==[compiled.Return of converted type from script]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Map conversions]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Map conversions]==])
set_tests_properties( [==[compiled.Map conversions]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Parse floats with non-posix locale]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Parse floats with non-posix locale]==])
set_tests_properties( [==[compiled.Parse floats with non-posix locale]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Mismatched numeric types only convert necessary params]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Mismatched numeric types only convert necessary params]==])
set_tests_properties( [==[compiled.Mismatched numeric types only convert necessary params]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.type_conversion to bool]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[type_conversion to bool]==])
set_tests_properties( [==[compiled.type_conversion to bool]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Make sure ChaiScript object still compiles / executes]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Make sure ChaiScript object still compiles / executes]==])
set_tests_properties( [==[compiled.Make sure ChaiScript object still compiles / executes]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test count tracer]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test count tracer]==])
set_tests_properties( [==[compiled.Test count tracer]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test stdlib options]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test stdlib options]==])
set_tests_properties( [==[compiled.Test stdlib options]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Pass r-value reference to func]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Pass r-value reference to func]==])
set_tests_properties( [==[compiled.Pass r-value reference to func]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Use unique_ptr]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Use unique_ptr]==])
set_tests_properties( [==[compiled.Use unique_ptr]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Call methods through unique_ptr]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Call methods through unique_ptr]==])
set_tests_properties( [==[compiled.Call methods through unique_ptr]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Call methods on base class through unique_ptr<derived>]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Call methods on base class through unique_ptr<derived>]==])
set_tests_properties( [==[compiled.Call methods on base class through unique_ptr<derived>]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test typed chaiscript functions to perform conversions]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test typed chaiscript functions to perform conversions]==])
set_tests_properties( [==[compiled.Test typed chaiscript functions to perform conversions]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test reference member being registered]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test reference member being registered]==])
set_tests_properties( [==[compiled.Test reference member being registered]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test unicode matches C++]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test unicode matches C++]==])
set_tests_properties( [==[compiled.Test unicode matches C++]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test returning by const non-reference]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test returning by const non-reference]==])
set_tests_properties( [==[compiled.Test returning by const non-reference]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test throwing and catching custom exception]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test throwing and catching custom exception]==])
set_tests_properties( [==[compiled.Test throwing and catching custom exception]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
add_test( [==[compiled.Test ability to get 'use' function from default construction]==] D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/compiled_tests.exe [==[Test ability to get 'use' function from default construction]==])
set_tests_properties( [==[compiled.Test ability to get 'use' function from default construction]==] PROPERTIES WORKING_DIRECTORY D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0)
set( compiled_tests_TESTS [==[compiled.C++11 Lambdas Can Be Registered]==] [==[compiled.Dynamic_Object attributes can be shared with C++]==] [==[compiled.Function objects can be created from chaiscript functions]==] [==[compiled.ChaiScript can be created and destroyed on heap]==] [==[compiled.Test automatic arithmetic conversions]==] [==[compiled.Generic exception handling with C++]==] [==[compiled.Throw an int]==] [==[compiled.Throw int or double]==] [==[compiled.Throw a runtime_error]==] [==[compiled.Throw unhandled type]==] [==[compiled.No unexpected exceptions leak]==] [==[compiled.Function ordering]==] [==[compiled.Functor cast]==] [==[compiled.Non-ASCII characters in the middle of string]==] [==[compiled.Non-ASCII characters in the beginning of string]==] [==[compiled.Non-ASCII characters in the end of string]==] [==[compiled.BOM in string]==] [==[compiled.Set and restore chai state]==] [==[compiled.Short comparison with int]==] [==[compiled.Test lookup of type names]==] [==[compiled.Simultaneous ChaiScript tests]==] [==[compiled.Utility_Test utility class wrapper]==] [==[compiled.Utility_Test utility class wrapper for enum]==] [==[compiled.Object copy counts]==] [==[compiled.Object lifetime tests]==] [==[compiled.Object lifetime test 2]==] [==[compiled.Test Derived->Base with non-polymorphic classes]==] [==[compiled.Variable Scope When Calling From C++]==] [==[compiled.Variable Scope When Calling From C++ 2]==] [==[compiled.Test long long dispatch]==] [==[compiled.Return of converted type from script]==] [==[compiled.Map conversions]==] [==[compiled.Parse floats with non-posix locale]==] [==[compiled.Mismatched numeric types only convert necessary params]==] [==[compiled.type_conversion to bool]==] [==[compiled.Make sure ChaiScript object still compiles / executes]==] [==[compiled.Test count tracer]==] [==[compiled.Test stdlib options]==] [==[compiled.Pass r-value reference to func]==] [==[compiled.Use unique_ptr]==] [==[compiled.Call methods through unique_ptr]==] [==[compiled.Call methods on base class through unique_ptr<derived>]==] [==[compiled.Test typed chaiscript functions to perform conversions]==] [==[compiled.Test reference member being registered]==] [==[compiled.Test unicode matches C++]==] [==[compiled.Test returning by const non-reference]==] [==[compiled.Test throwing and catching custom exception]==] [==[compiled.Test ability to get 'use' function from default construction]==])
