# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "OFF")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_IFW "OFF")
SET(CPACK_BINARY_NSIS "ON")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_PRODUCTBUILD "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TXZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "OFF")
SET(CPACK_BINARY_ZIP "OFF")
SET(CPACK_BUILD_SOURCE_DIRS "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0;D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0")
SET(CPACK_CMAKE_GENERATOR "MinGW Makefiles")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
SET(CPACK_DEBIAN_PACKAGE_SECTION "devel")
SET(CPACK_GENERATOR "7Z;ZIP")
SET(CPACK_IGNORE_FILES "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0;\\.svn;\\.git;.swp;.*~")
SET(CPACK_INSTALLED_DIRECTORIES "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/chaiscript")
SET(CPACK_MODULE_PATH "")
SET(CPACK_NSIS_DISPLAY_NAME "chaiscript 6.1.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "chaiscript 6.1.0")
SET(CPACK_OUTPUT_CONFIG_FILE "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "contact@chaiscript.com")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/description.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "An embedded scripting language for C++")
SET(CPACK_PACKAGE_EXECUTABLES "chai;ChaiScript Eval")
SET(CPACK_PACKAGE_FILE_NAME "chaiscript-6.1.0-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "chaiscript 6.1.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "chaiscript 6.1.0")
SET(CPACK_PACKAGE_NAME "chaiscript")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "ChaiScript.com")
SET(CPACK_PACKAGE_VERSION "6.1.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "6")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/license.txt")
SET(CPACK_RESOURCE_FILE_README "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/readme.md")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-3.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_PACKAGE_GROUP "Programming")
SET(CPACK_RPM_PACKAGE_LICENSE "BSD")
SET(CPACK_RPM_PACKAGE_SOURCES "ON")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "ON")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "7Z;ZIP")
SET(CPACK_SOURCE_IGNORE_FILES "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0;\\.svn;\\.git;.swp;.*~")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "chaiscript-6.1.0-Source")
SET(CPACK_SOURCE_RPM "")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "win32-Source")
SET(CPACK_SOURCE_TXZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "D:/cvs/gameapi-code/GameApi/GameApi/chai/ChaiScript-6.1.0/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
